image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test
  - test_build
  - build
  - upload_image

variables:
    PSQL_VERSION: "9.5"
    VERSION: "11.0"
    TRAVIS_PYTHON_VERSION: "3.6"
    ODOO_REPO: "vauxoo/odoo"
    ODOO_BRANCH: "11.0"
    BASE_IMAGE: "vauxoo/odoo-110-image"
    COUNTRY: "MX"
    http_proxy: http://172.17.0.1:3128
    https_proxy: http://172.17.0.1:3128
    ftp_proxy: http://172.17.0.1:3128

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - sudo apt-get update && sudo apt-get install -y dos2unix
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source /.repo_requirements/virtualenv/python3.6/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests


test:
  stage: test
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    INCLUDE: "test_app_github"
    INSTALL: "test_app_github"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - apt-get update && apt-get install -y tree dos2unix
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source /.repo_requirements/virtualenv/python3.6/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc

build:
  stage: build
  tags:
    - build
  variables:
    INSTALL: "test_app_github"
    CUSTOMER: "test_app_github"

  script:
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools test_images

upload_image:
  stage: upload_image
  only:
      - 11.0@vauxoo/test_app_github
  when: on_success
  tags:
    - build
  variables:
    CUSTOMER: "test_app_github"
  script:
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools upload_image
